export const ar = {
    auth: {
        enterMobile:"يرجى إدخال رقم الموبيل",
        mobileMesg:"لقد أدخلت رقم خاطئ",
        mobileValidation:"رقم  الهاتف يجب ان يكون 11 رقم",
        login: 'تسجيل الدخول',
        logout: 'تسجيل الخروج',
        email: 'بريد الكتروني',
        rememberMe: 'تذكرني',
        signUp:'إنشاء حساب',
        OrganizationNameinEnglish:"اسم المنظمة باللغة الإنجليزية",
        OrganizationNameinArabic:"اسم المنظمة باللغة العربية",
        pleaseenternameinEnglish:"تنسيق خاطئ ، يرجى إدخال الاسم باللغة الإنجليزية",
        pleaseenternameinArabic:"تنسيق خاطئ ، يرجى إدخال الاسم باللغة العربية",
        EnteryourOrganizationData:"أدخل بيانات المنظمة الخاصة بك",
        ChooseyourOrganizationFiled:"اختار مجال منظمتك",
        OrganizationfromDropDownmenu:"اختر منظمتك من القائمة",
        ConutryfromDropDownmenu:"اختر بلدك من القائمة",
        CityfromDropDownmenu:"اختر مدينتك من القائمة",
        EnteryourAdminData:"أدخل بيانات المسؤل الخاص بك",
        AddressinEnglish:"العنوان باللغة الإنجليزية",
        AddressinArabic:"العنوان باللغة العربية",
        wrongformatpleaseaddressinArabic:"تنسيق خاطئ، يرجى العنوان باللغة العربية",
        wrongformatpleaseaddressinEnglish:"  تنسيق خاطئ، يرجى العنوان باللغة الإنجليزية",
        ChooseyourCountry:"اختر بلدك",
        ChooseyourCity:"اختر مدينتك",
        FirstName:"الاسم الاول",
        lastName:"الاسم الاخر",
        wrongformat:"تنسيق خاطئ",
        Password:"كلمة السر",
        passwordConfirm:"تأكيد كلمة السر",
        namemustbemin3characters:"يجب أن يكون الاسم 3 أحرف كحد أدنى",
        namecantacceptspace:"لا يسمح باستخدام مسافة",
        namecantacceptspecialcharacters:"لا يسمح باستخدام حروف خاصة",
        namecantacceptnumbers:"لا يسمح باستخدام ارقام",
        mobile:"رقم الهاتف",
        passwordmustbemincharacters:"كلمة السر يجب الا تقل عن 8 حروف",
        passwordmustbemax20characters:"كلمة السر لا يجب ان تزيد عن 20 حرف",
        IagreetotheTermsandConditions:"اوافق على الشروط",
        Passwordexpresion:"كلمة السر يجب ان تحتوى على حرف كبير وحرف صغير ورمز خاص ورقم ",
        password_placeholder: 'ادخل رقمك السري',
        mail_massage:'هذا البريد الالكتروني غير صالح',
        mail_req_massage:'الرجاء ادخال بريدك الالكتروني',
        password:'الرقم السري',
        forgetPassword:'نسيت كلمه السر؟',
        IagreetotheTermsandConditions:"اوافق على الشروط والاحكام",
        Verify:"تحقق من رقمك",
        VerifyBtn:"تحقق",
        ResendCode:"اعادة ارسال الرمز",
        digitssenttoyourmobiletologin:"الرجاء إدخال 6 أرقام مرسلة إلى هاتفك المحمول لتسجيل الدخول",
        yourcodewillbesentin:"سيتم إرسال رمز التاكيد بك في",
         passwordMassage:'الرجاء ادخال كلمه السر',
    },
  
    header : {
        Home : 'الرئيسية',
        About : 'عن دورك',
        ContactUs : 'تواصل معنا',
        BusinessOwners : ' صاحب عمل؟',
        login : 'تسجيل الدخول ',
        signUp:'إنشاء حساب'
    },
    errors:{
        Unauthorized:'غير مصرح',
        sorry401:'ناسف لا يمكن تنفيذ هذه العمليه',
        goToHome:' الرجوع للصفحه الرئيسية',
        sorry403:'نأسف ، لكن ليس لديك حق الوصول إلى هذه الصفحة أو المورد.',
        Access:'غير مسموح بالدخول',
        notFound:'لم يتم الوصول للصفحه',
        error_text:'الصفحه التي تبحث عنها ربما تكون قد تم حذفهااو تم تغيير اسمها او غير متاحه حاليا',
        serverError:'خطا بالخادم',
    }, 

}