
export const en = {
    auth: {
        enterMobile:"Enter your mobile number ",
        mobileMesg:"you entered a wrong number ",
        mobileValidation:"Mobile Number Must Be 11 Digits",
        login: 'login',
        logout: 'Logout',
        signUp:'Sign Up',
        OrganizationNameinEnglish :"Organization Name in English ",
        OrganizationNameinArabic:"Organization Name in Arabic",
        pleaseenternameinEnglish:"wrong format, please enter name in English",
        pleaseenternameinArabic:"wrong format, please enter name in Arabic",
        ChooseyourOrganizationFiled:"Choose your Organization Filed",
        OrganizationfromDropDownmenu:"Choose your Organization from Drop Down menu",
        ConutryfromDropDownmenu:"Choose your Conutry from Drop Down menu",
        CityfromDropDownmenu:"Choose your city from Drop Down menu",
        EnteryourAdminData:"Enter your Admin Data",
        AddressinEnglish:"Address in English",
        AddressinArabic:"Address in Arabic",
        wrongformatpleaseaddressinEnglish:"wrong format, please address in English",
        wrongformatpleaseaddressinArabic:"wrong format, please address in Arabic",
        ChooseyourCountry:"Choose your Conutry",
        ChooseyourCity:"Choose your City",
        EnteryourOrganizationData:"Enter your Organization Data",
        rememberMe: 'Remember me',
        email: 'Email',
        mail_massage: 'The input is not valid E-mail!',
        mail_req_massage: 'Please input your E-mail!',
        FirstName:"First Name",
        lastName:"last Name",
        wrongformat:"wrong format",
        Password:"Password",
        passwordConfirm:"password Confirm",
        namemustbemin3characters:"name must be min 3 characters",
        namecantacceptspace:"name can't accept space",
        namecantacceptspecialcharacters:"name can't accept  special characters",
        namecantacceptnumbers:"name can't accept numbers",
        IagreetotheTermsandConditions:"I agree to the Terms and Conditions",
        password_placeholder:'Enter your password', 
        plaeaseEnterMail:'Please Enter your email then click the button below to request another one.',
        password:'Password',
        mobile:"mobile",
        passwordmustbemincharacters:"password must be min 8 characters",
        passwordmustbemax20characters:"password must be max 20 characters",
        Passwordexpresion:"Password must contaian at lest one lower case letter, one upper case letter, one digit and one special character",
        forgetPassword:'Forget Password?',
        IagreetotheTermsandConditions:"I agree to the Terms and Conditions",
        Verify:"Verify your number",
        VerifyBtn:"Verify",
        ResendCode:"Resend Code",
        digitssenttoyourmobiletologin:"Please enter 6 digits sent to your mobile to login",
        yourcodewillbesentin:"your code will be sent in",
        passwordMassage:'Please input your password!',
    },
    header : {
        Home : 'Home',
        About : 'About',
        ContactUs : ' Contact Us',
        BusinessOwners : 'Business Owners?',
        login : 'Login',
        signUp:'Sign Up'
    },
    errors:{
        goToHome:'Back Home',
    }
 }